version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
    - 7.26.2
    - 7.26.3
  - dependency-name: unsplash-js
    versions:
    - 7.0.3
    - 7.0.4
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.1
  - dependency-name: ember-data
    versions:
    - 3.24.0
    - 3.25.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
  - dependency-name: ember-template-lint
    versions:
    - 2.17.0
    - 2.18.0
    - 2.18.1
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
  - dependency-name: ember-fetch
    versions:
    - 8.0.4
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: ember-cli
    versions:
    - 3.24.0
  - dependency-name: ember-auto-import
    versions:
    - 1.10.1
  - dependency-name: "@glimmer/component"
    versions:
    - 1.0.3
  - dependency-name: "@glimmer/tracking"
    versions:
    - 1.0.3
  - dependency-name: ini
    versions:
    - 1.3.8
  commit-message:
    prefix: "[skip netlify]"
